### ISSUE TITLE
Add details how to test the watchface

### ISSUE THREAD

**Issue by maxistar** [Gumix/huawei-band-6-watch-faces#1]
Thanks for the great project. I wonder is it possible to test it on the physical device? I just bought Huawei Band 7 and trying to figure out how I can install the custom watchface on it. Is this really possible?

**Comment by Gumix** [comment]
Эти `*.hwt` файлы сделаны для Band 6, я не знаю можно ли их загрузить в Band 7 или надо перекомпилировать.

Все инструкции тут: https://4pda.to/forum/index.php?showtopic=1017265
